# Generated by Django 3.1.4 on 2020-12-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20201211_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.DurationField(null=True),
        ),
    ]
