# Generated by Django 3.1.4 on 2020-12-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_auto_20201211_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'Пользователь с таким электронным адресом уже существует'}, max_length=254, null=True, unique=True),
        ),
    ]
