# Generated by Django 3.1.4 on 2020-12-21 09:14

from django.db import migrations, models
import user_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_auto_20201214_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='username',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=user_auth.models.get_photo_upload_path),
        ),
    ]
